[info]
first_name = "Eric Samuel"
last_name = "Londres"
phone = "(848) 224-1664"
email = "EricLondres@outlook.com"
website = "EricLondres.tech"

[education]
when = "Aug 2017 -- May 2021"
degree = "Computer Science"
university = "Stevens Institute of Technology"
city = "Hoboken, NJ"
descriptions = [ "Presidential Scholarship", "Relevant Coursework: Algorithms; Data Structures; Concurrent Programming; Human--Computer Interaction; Database Management Systems; Compiler Design \\& Implementation; Operating Systems" ]

[skills]
languages = "Bash, C, C\\#, C++, Erlang, Go, Java, JavaScript, Lisp, OCaml, PHP, Python, Rust"
web = "HTML, CSS/SASS, React, Svelte, Express"
tech = "GNU/Linux, Git, Node, GitLab CI, SQL, MongoDB, GCP, AWS"

[[work]]
when = "Aug 2020 -- Dec 2020"
title = "Course Assistant"
employer = "Stevens Institute of Technology"
city = "Hoboken, N.J."
[[work.description]]
has_tags = false
text = "Introduced and expanded content to students for the graduate course Concurrent Programming"
[[work.description]]
has_tags = false
text = "Assisted the course professor in designing test questions for tests the students will take"
[[work.description]]
has_tags = false
text = "Planned course content and decided what needs to be taught"
[[work.description]]
has_tags = false
text = "Devised and implemented effective ways to demonstrate course material"

[[work]]
when = "Jun 2019 -- Aug 2020"
title = "Student Assistant"
employer = "Stevens Institute of Technology"
city = "Hoboken, N.J."
[[work.description]]
has_tags = false
text = "Developed software for the Reinventing Civil Defense research project"
[[work.description]]
has_tags = true
tags = "PHP, SQL, JQuery"
text = "Planned, developed, and maintained a complex web application to allow a speaker to create an interactive experience set in a nuclear war"
[[work.description]]
has_tags = true
tags = "React"
text = "Designed and implemented several event--specific websites"
[[work.description]]
has_tags = false
text = "Led development on a virtual reality project using Unity which visualizes the scale and scope of a nuclear detonation in New York City"
[[work.description]]
has_tags = false
text = "Introduced several new technologies to the workplace that substantially improved developer productivity and code quality, including Git, GitLab CI/CD, and modern JavaScript"

[[leadership]]
when = "Mar 2019 -- Mar 2020"
title = "President"
employer = "SITTV"
city = "Hoboken, N.J."
[[leadership.description]]
has_tags = false
text = "Oversaw the operations of the organization and handled administrative responsibilities"
[[leadership.description]]
has_tags = false
text = "Fostered a healthy and productive environment for other executive officers and organization members"
[[leadership.description]]
has_tags = false
text = "Organized \\& chaired events, including public events and executive board meetings"
[[leadership.description]]
has_tags = false
text = "Communicated on behalf of the organization to outside groups, including contract negotiations, budget defenses, and business meetings"

[[leadership]]
when = "Dec 2018 -- Dec 2019"
title = "Webmaster"
employer = "Alpha Phi Omega --- Theta Alpha Chapter"
city = "Hoboken, N.J."
[[leadership.description]]
has_tags = true
tags = "PHP, MySQL"
text = "Managed a web application used by hundreds of users on a daily basis"
[[leadership.description]]
has_tags = false
text = "Introduced new technologies such as \bbold{Cloudflare}; reduced page load times by over 90\%, and lowered initial paint times to less than 1 second while increasing developer efficiency"
[[leadership.description]]
has_tags = false
text = "Recruited, trained, and led a team of junior developers"
[[leadership.description]]
has_tags = true
tags = "React"
text = "Designed and began implementation of a large--scale web application using modern technologies such as \bbold{Google Firebase} and user experience design using \bbold{Balsamiq}"

[[leadership]]
when = "Mar 2018 -- Mar 2019"
title = "Director of Deliverables"
employer = "SITTV"
city = "Hoboken, N.J."
[[leadership.description]]
has_tags = false
text = "Designed and implemented a cable video streaming platform for an audience of 1,500 viewers"
[[leadership.description]]
has_tags = false
text = "Recruited and trained members in the use of video editing software"
[[leadership.description]]
has_tags = false
text = "Employed, trained, and oversaw a team of systems administrators"
